/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "./_components/navBar/page";
import Link from "next/link";


const figtree = Figtree({
  variable: "--font-figtree-sans",
  subsets:["latin"],
  weight:["300","400","500"]

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${figtree.variable} antialiased relative`}
      >
         <Link href={"https://wa.me/212660112597?text=Hello%20there!"} className="w-16 z-50 h-16 cursor-pointer bottom-8 right-8 fixed" >
        <img src="/icons/whatsapp.png" className="w-16 h-16" alt="" />
        </Link >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <div className="dark:bg-dark overflow-hidden">
           <NavBar />
           {children}
           </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
